### PR TITLE
Some work on the design

### PR DESCRIPTION
**Pull request by jjjjjjjjjjjjjjjjjjjj**
Hello, 

Here's another pull request. Keep in mind that this is a work in progress, so there's a bunch of adjustments to be made. Also, check your e-mail inbox!

### CODE REVIEW

**Comment by janneklouman** [comment]
I pushed some more commits. Starting to look like the design material that I have, apart from some missing fonts. We should probably update the `.Site.Params.addthis` variable in `config.toml` to represent an account that you own (addthis.com - right now it's running on my account). Have a look and give some feedback! Looks like a bunch of old commits that have already been merged made it into this PR as well, apologies for that.

Have a nice evening!
Janne

**Comment by Andrey9kin** [comment]
Hey @janneklouman nicely done! I think we are few steps away from being ready. Do you have anything else in mind that you would like to add?

I have only two things that I can think of - video seems to be too tall, i.e. I can't see sign up input form for the landing page; text for the email input "The automation blog Sign up here for our newsletter" and text at the author page "Etiam porta sem malesuada magna mollis euismod." seems to not scale when going to mobile formats. Is it something you can look into?

**Comment by janneklouman** [comment]
Hey! 

I totally agree. The site needs to be responsive (which is barely handled at the moment). I don't have any design material for this but I will give it a shot this weekend! 

One solution to the video being too tall that comes to mind is to cap it at 100% (or less) of the viewport height, and then crop it top/bottom - at the risk of losing the chain/some of the sign. What do you think?

I can't think of anything else right now, apart from perhaps loading the video in different resolutions based on screen size (it looks a bit grainy to me in high res) - but that's always a dilemma I guess, speed versus image/video quality (and page weight). I'll try to think of more!

Have a nice evening,
Janne

**Comment by janneklouman** [comment]
Hello!

I forgot to comment after my last push which contains an update for the mobile view. If you have time please have a look! 

Also: do you have any thoughts about capping the video height to `x`% of the viewport height, at the cost of video content? One alternative (without having separate videos) is to cap its width, leaving space on the sides (could perhaps be filled with a color, image, or something).

**Comment by Andrey9kin** [comment]
@janneklouman Hey! Looks good! I think it is fine to cut video a by %x of its height - we have enough empty space at the top. BTW, would it be possible to cut a little bit from the bottom and a little bit from the top? I'm asking because there is a room for cutting at the bottom too

Let's get that fixed and then we can consider it done!

**Comment by janneklouman** [comment]
Great! 

Yes definitely, I'm thinking equal amounts top/bottom crop. I'll get on it, expect result later this week.

**Comment by janneklouman** [comment]
Perhaps this was more easily achieved than I expected. I haven't had a chance to try this on very large screens (but I did poke around a bit in chrome dev tools). Please have a look when you have the chance!

**Pull request closed without merging**
